
services:

#   frontend:
#     image: antoniopapa1991/admin-frontend
#     ports:
#       - 8080:80
#     depends_on:
#       - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db


  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  dbdata_admin:
    image: adminer
    restart: always
    volumes:
      - ./storage/dbdata_admin:/var/lib/adminer
    depends_on:
      - db
    ports:
      - 8081:8080




