apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    app: kuard-app
spec:
  containers:
    - name: my-pod-kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      ports:
        - containerPort: 8081
          name: http
          protocol: TCP
