# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Deploy PHP app (Laravel) to Azure VM - laravel-admin

on:
  push:
    branches:
      - main
      - feature/dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'

    steps:
      # Clone the repository
      - name: Check code
        uses: actions/checkout@v3

      # Install Docker on the GitHub runner
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Docker login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up SSH key for VM connection
      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      # Deploy the Laravel app via Docker on Azure VM
      - name: Deploy Laravel app via Docker on Azure VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
        run: |
          ssh -T -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_IP 'echo "SSH connection successful"'

          ssh -T -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_IP << EOF
            mkdir -p /home/$VM_USER/sosk_workshop
            cd /home/$VM_USER/sosk_workshop
            docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-admin:v1.0.0
            docker build -t laravel-admin:v1.0.0 .
            docker run -d -p 8000:8000 laravel-admin:v1.0.0
          EOF

























































# echo "123456789" | docker login -u bastiannebra --password-stdin
# ssh -i ~/.ssh/sosk_key.pem azureuser@20.199.18.244









