name: Build and Push Laravel to Docker Hub

env:
  TAG_NAME: laravel-admin:v1.1.0

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Vérifiez le code source
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configuration Docker Login
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construire l'image Docker
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$TAG_NAME .

    # Pousser l'image sur Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/$TAG_NAME


