# CodeSniffer ist ein Tool, das in der Softwareentwicklung verwendet wird, um sicherzustellen, 
# dass der Quellcode bestimmten Codierungsstandards entspricht. Es hilft dabei, die Qualität, 
# Konsistenz und Lesbarkeit des Codes zu wahren, indem es Verstöße gegen festgelegte Regeln 
# oder Richtlinien erkennt.

name: "Laravel Code Style Test workflow"

on:
  push:
    branches:
        - main
  workflow_dispatch:
    inputs:
      name:
        description: "Specify the job name"
        required: false
        type: string
        default: "Run Laravel Tests"
  workflow_call:
    inputs:
      name:
        description: "Specify the job name"
        required: false
        type: string
        default: "Run Laravel Tests"
      code_directory:
        description: "Directory to check"
        required: false
        type: string
      php_version:
        description: "PHP version for the app"
        type: string
        default: '8.0'

jobs:
  laravel-tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ inputs.php_version }}
          
      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install PHP CodeSniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Check PHP CodeSniffer path
        run: echo $(which phpcs)

      - name: Run PHP Code Style Test
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 --report=checkstyle --report-file=$(pwd)/phpcs-report.xml app/

      - name: Fix PHP Code Style
        run: ~/.composer/vendor/bin/phpcbf --standard=PSR12 --report=checkstyle --report-file=phpcs-report.xml app/

      - name: Upload PHPCS Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: phpcs-report
          path: phpcs-report.xml
